"use client";

import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import AppWalletProvider from "./wallet/AppWalletProvider";
import { AppProvider } from "./context/AppContext";
import Footer from "./components/Footer";
import { usePathname } from "next/navigation"; // Updated
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname(); // Get the current pathname
  const isWelcomePage = pathname === "/"; // Check if it's the Welcome page

  return (
    <html lang="en">
      <body className="font-sans">
        <AppWalletProvider>
          <AppProvider>
            <div
              className={
                isWelcomePage
                  ? "gradient-bg" // Home page gradient
                  : "gradient-bg-light" // Bright mode gradient for all other pages
              }
            >
              <Navbar isLightMode={!isWelcomePage}/>
              {children}
            </div>
          </AppProvider>
        </AppWalletProvider>

        <Footer />
        <ToastContainer />
      </body>
    </html>
  );
}